version: '3.8'

services:
  postgres:
    image: postgres:smartway
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - griff_db_data:/var/lib/postgresql/data

volumes:
  griff_db_data: